engines:
  fixme: { enabled: true }
  gofmt: { enabled: true }
  golint: { enabled: true }
  govet: { enabled: true }
exclude_paths:
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
ratings:
  paths:
    - "**.go"